baseURL = 'https://tcluri.github.io/'
title = 'tcluri:$'

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

# Remove files from destination not found in static directories
cleandestinationdir = true

enableEmoji = true

languageCode = 'en-us'

disableFastRender = true

[module]
  [[module.imports]]
    path = "gitlab.com/kaushalmodi/hugo-theme-refined"

[Author]
  name = "Tejaa Chintaluri"
  homepage = "https://tcluri.github.io/"

[Social]
  github = "tcluri"
  twitter = "tcluri_"

[Params]
  tagline = "My random notes"

  # Go date formats: https://golang.org/pkg/time/#pkg-constants
  dateform = "Mon Jan 2, 2006"

  # Set favicons to true only if the following files are present in the project assets/ dir:
  # - safari-pinned-tab.svg
  # - manifest.json
  # - favicon-16x16.png
  # - favicon-32x32.png
  # - apple-touch-icon.png
  favicons = false

  themecolorbase = "blue" # Valid values: "red", "orange", "yellow", "green", "cyan", "blue", "magenta", "brown"

  [Params.source]
    url = "https://github.com/tcluri/tcluri.github.io"

    [[Params.social.service]]
      name = "Github"
      link = "https://github.com/tcluri/"
      relme = true
    [[Params.social.service]]
      name = "Twitter"
      link = "https://twitter.com/tcluri_/"

[markup]
  [markup.highlight]
    codeFences = true # default = true
    lineNumbersInTable = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
